#!/bin/sh

term=urxvt
qemu=qemu-system-x86_64
smp=4
mem=512m

qemu_cmd="$qemu -smp $smp -m $mem \
        -hda obj/cox-bootimage \
        -serial file:obj/cox-serial.log \
        -net nic,model=e1000 -net user,hostfwd=tcp::9999-:7 -net dump,file=obj/cox-netdump.pcap"

if [ "$1" = "gdb" ]; then
    $qemu_cmd -vga std -s -S &
    ucore-mp64-gdb
elif [ "$1" = "console" ]; then
    $qemu_cmd -vga std -S -monitor stdio
elif [ "$1" = "3w" ]; then
    $term -e $qemu_cmd -vga std -monitor stdio -s -S &
    ucore-mp64-gdb
fi
