#ifndef __ARCH_ASM_MACH_H__
#define __ARCH_ASM_MACH_H__

#define _MACH_PAGE_SIZE  4096
#define _MACH_PAGE_SHIFT 12

#define _MACH_BYTE_ENDIAN _MACH_BYTE_ENDIAN_LITTLE
#define _MACH_STACK_ORDER _MACH_STACK_ORDER_DEC

#endif
